site_name: Renovate Docs
site_url: 'https://docs.renovatebot.com'

# Theme settings
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo: '/assets/images/logo.png'
  favicon: '/assets/images/logo.png'

extra_css:
  - '/assets/css/style.css'

extra_javascript:
  - '/assets/js/fx.js'

# Extensions
markdown_extensions:
  - meta

# Page Tree
pages:
  - Getting Started:
      - 'GitHub App Installation': '/install-github-app.md'
      - 'GitLab App Installation': '/install-gitlab-app'
      - 'Configure Renovate (Onboarding PR)': '/configure-renovate'
      - 'Private npm module support': '/private-modules'
      - 'Reconfiguring Renovate': '/reconfigure-renovate'
  - Configuration Options: '/configuration-options'
  - Self Hosted Configuration: '/self-hosted-configuration'
  - Shareable Config Presets: '/config-presets'
  - Language Support:
      - 'Bazel': '/bazel'
      - 'Docker': '/docker'
      - 'Golang': '/golang'
      - 'Java': '/java'
      - 'JavaScript': '/javascript'
      - 'Node.js Versions': '/node'
      - 'Nuget': '/nuget'
      - 'PHP': '/php'
      - 'Python': '/python'
      - 'Ruby': '/ruby'
  - Deep Dives:
      - 'Should you Pin your Javascript Dependencies?': '/dependency-pinning'
      - 'Config Template Editing': '/configuration-templates'
      - 'Updating and Rebasing Branches': '/updating-rebasing'
      - 'Semantic Commit Messages': '/semantic-commits'
      - 'Noise Reduction': '/noise-reduction'
  - Config Presets:
      - 'Full Config Presets': '/presets-config'
      - 'Default Presets': '/presets-default'
      - 'Docker Presets': '/presets-docker'
      - 'Group Presets': '/presets-group'
      - 'Helper Presets': '/presets-helpers'
      - 'JS Presets': '/presets-js'
      - 'Meteor Presets': '/presets-meteor'
      - 'Monorepo Presets': '/presets-monorepo'
      - 'Package Presets': '/presets-packages'
      - 'Preview Presets': '/presets-preview'
      - 'Schedule Presets': '/presets-schedule'
  - Renovate Pro:
      - 'Overview': '/pro/overview'
      - 'Configuration (GitHub)': '/pro/configuration-github'
      - 'Configuration (GitLab)': '/pro/configuration-gitlab'
      - 'Advanced Details': '/pro/advanced'
  - All Other:
      - 'Data Security and Handling': '/data-security'
      - 'Frequently Asked Questions (FAQ)': '/faq'
